# Save this as generate_dinner_recipes_corrected.py
import csv
import random
import json

BASE_RECIPES_CSV_CONTENT = """
0,"Spaghetti and Meatballs","[""1 lb. spaghetti"", ""1 lb. ground beef"", ""1 egg"", ""1/4 c. breadcrumbs"", ""1/4 c. grated Parmesan cheese"", ""1 (24 oz.) jar marinara sauce""]","[""Cook spaghetti according to package directions."", ""In a bowl, combine ground beef, egg, breadcrumbs, and Parmesan cheese. Form into meatballs."", ""Brown meatballs in a large skillet. Drain fat."", ""Pour marinara sauce over the meatballs, bring to a simmer, and cook for 15 minutes."", ""Serve the meatballs and sauce over the cooked spaghetti.""]","www.example-dinner.com/recipe/0","Generated","[""spaghetti"", ""ground beef"", ""egg"", ""breadcrumbs"", ""Parmesan cheese"", ""marinara sauce""]"
1,"Classic Beef Tacos","[""1 lb. ground beef"", ""1 packet taco seasoning"", ""12 hard taco shells"", ""1 c. shredded lettuce"", ""1 c. diced tomatoes"", ""1 c. shredded cheddar cheese"", ""salsa and sour cream for topping""]","[""In a skillet, cook ground beef until browned. Drain the fat."", ""Stir in the taco seasoning and water according to the packet's directions. Simmer for 5 minutes."", ""Warm the taco shells in the oven."", ""Fill each shell with the seasoned beef, then top with lettuce, tomatoes, cheese, salsa, and sour cream.""]","www.example-dinner.com/recipe/1","Generated","[""ground beef"", ""taco seasoning"", ""taco shells"", ""lettuce"", ""tomatoes"", ""cheddar cheese"", ""salsa"", ""sour cream""]"
2,"Simple Baked Salmon","[""2 (6 oz.) salmon fillets"", ""1 Tbsp. olive oil"", ""1 tsp. garlic powder"", ""1/2 tsp. salt"", ""1/4 tsp. black pepper"", ""1 lemon, sliced""]","[""Preheat oven to 400°F (200°C)."", ""Place salmon fillets on a baking sheet lined with foil."", ""Drizzle with olive oil and sprinkle with garlic powder, salt, and pepper."", ""Top each fillet with a few lemon slices."", ""Bake for 12-15 minutes, or until the salmon is cooked through and flakes easily with a fork.""]","www.example-dinner.com/recipe/2","Generated","[""salmon"", ""olive oil"", ""garlic powder"", ""salt"", ""pepper"", ""lemon""]"
3,"Chicken Alfredo","[""1 lb. fettuccine"", ""1 lb. boneless, skinless chicken breast, cut into bite-sized pieces"", ""2 Tbsp. butter"", ""1 pint heavy cream"", ""1 c. grated Parmesan cheese"", ""2 cloves garlic, minced"", ""salt and pepper to taste""]","[""Cook fettuccine according to package directions."", ""While pasta cooks, season chicken with salt and pepper. Melt butter in a large skillet and cook chicken until golden and cooked through. Remove chicken from skillet."", ""In the same skillet, add garlic and cook for 30 seconds. Add heavy cream and bring to a simmer. Cook for 3-5 minutes until it thickens."", ""Stir in Parmesan cheese until the sauce is smooth. Season with salt and pepper."", ""Return the chicken to the skillet, add the drained pasta, and toss to coat.""]","www.example-dinner.com/recipe/3","Generated","[""fettuccine"", ""chicken breast"", ""butter"", ""heavy cream"", ""Parmesan cheese"", ""garlic"", ""salt"", ""pepper""]"
4,"Homemade Hamburgers","[""1 lb. ground beef"", ""1/2 tsp. salt"", ""1/4 tsp. black pepper"", ""4 hamburger buns"", ""lettuce, tomato, onion slices for topping""]","[""Gently combine ground beef, salt, and pepper. Form into 4 patties."", ""Grill or pan-fry the patties over medium-high heat for 4-5 minutes per side, or until cooked to desired doneness."", ""Serve on hamburger buns with your favorite toppings.""]","www.example-dinner.com/recipe/4","Generated","[""ground beef"", ""salt"", ""pepper"", ""hamburger buns"", ""lettuce"", ""tomato"", ""onion""]"
5,"Vegetable Lasagna","[""9 oven-ready lasagna noodles"", ""1 (15 oz.) container ricotta cheese"", ""2 c. shredded mozzarella cheese"", ""1/2 c. grated Parmesan cheese"", ""1 egg"", ""1 (24 oz.) jar marinara sauce"", ""2 c. chopped vegetables (spinach, zucchini, bell peppers)""]","[""Preheat oven to 375°F (190°C)."", ""In a bowl, mix together ricotta cheese, 1 cup of mozzarella, Parmesan, and the egg."", ""Spread a thin layer of marinara sauce in the bottom of a 9x13 inch baking dish."", ""Layer with 3 noodles, half of the ricotta mixture, half of the vegetables, and a layer of sauce."", ""Repeat the layers. Top with the final 3 noodles, the remaining sauce, and the remaining 1 cup of mozzarella cheese."", ""Bake for 45 minutes, or until bubbly and golden.""]","www.example-dinner.com/recipe/5","Generated","[""lasagna noodles"", ""ricotta cheese"", ""mozzarella cheese"", ""Parmesan cheese"", ""egg"", ""marinara sauce"", ""spinach"", ""zucchini"", ""bell peppers""]"
6,"Chicken Parmesan","[""2 boneless, skinless chicken breasts, pounded thin"", ""1 c. breadcrumbs"", ""1/2 c. Parmesan cheese"", ""1 egg, beaten"", ""1/2 c. flour"", ""1 c. marinara sauce"", ""1 c. shredded mozzarella cheese""]","[""Preheat oven to 400°F (200°C)."", ""Set up three shallow dishes: one with flour, one with the beaten egg, and one with breadcrumbs mixed with Parmesan."", ""Dredge each chicken breast in flour, then egg, then breadcrumbs."", ""Pan-fry the chicken in a little oil for 2-3 minutes per side until golden. Place in a baking dish."", ""Top each breast with marinara sauce and mozzarella cheese."", ""Bake for 15-20 minutes, until cheese is melted and bubbly.""]","www.example-dinner.com/recipe/6","Generated","[""chicken breast"", ""breadcrumbs"", ""Parmesan cheese"", ""egg"", ""flour"", ""marinara sauce"", ""mozzarella cheese""]"
7,"Shepherd's Pie","[""1 lb. ground beef"", ""1 onion, chopped"", ""1 c. frozen mixed vegetables (peas and carrots)"", ""1 (10 oz.) can beef gravy"", ""2 c. prepared mashed potatoes"", ""1/2 c. shredded cheddar cheese""]","[""Preheat oven to 375°F (190°C)."", ""In a skillet, cook ground beef and onion until browned. Drain fat."", ""Stir in the mixed vegetables and gravy. Bring to a simmer and pour into a casserole dish."", ""Spread the mashed potatoes evenly over the meat mixture."", ""Sprinkle with cheddar cheese."", ""Bake for 20-25 minutes, or until heated through and the top is golden.""]","www.example-dinner.com/recipe/7","Generated","[""ground beef"", ""onion"", ""mixed vegetables"", ""beef gravy"", ""mashed potatoes"", ""cheddar cheese""]"
8,"Beef and Broccoli Stir-Fry","[""1 lb. flank steak, thinly sliced"", ""1 head of broccoli, cut into florets"", ""1/4 c. soy sauce"", ""2 Tbsp. honey"", ""1 Tbsp. cornstarch"", ""2 cloves garlic, minced"", ""1 Tbsp. vegetable oil""]","[""In a small bowl, whisk together soy sauce, honey, cornstarch, and garlic."", ""Heat oil in a large skillet or wok over high heat. Add the steak and cook until browned. Remove from skillet."", ""Add broccoli florets to the skillet with a few tablespoons of water. Cover and steam for 3-4 minutes."", ""Return the steak to the skillet. Pour the sauce over everything and stir-fry for 1-2 minutes until the sauce thickens."", ""Serve immediately over rice.""]","www.example-dinner.com/recipe/8","Generated","[""flank steak"", ""broccoli"", ""soy sauce"", ""honey"", ""cornstarch"", ""garlic"", ""vegetable oil""]"
9,"Shrimp Scampi","[""1 lb. spaghetti"", ""1 lb. large shrimp, peeled and deveined"", ""4 Tbsp. butter"", ""4 cloves garlic, minced"", ""1/2 c. dry white wine or chicken broth"", ""Juice of 1 lemon"", ""2 Tbsp. chopped parsley""]","[""Cook spaghetti according to package directions."", ""In a large skillet, melt butter over medium heat. Add garlic and cook for 1 minute."", ""Add the shrimp and cook for 2-3 minutes until pink."", ""Pour in the white wine and lemon juice. Bring to a simmer."", ""Toss the drained pasta with the shrimp sauce. Sprinkle with parsley before serving.""]","www.example-dinner.com/recipe/9","Generated","[""spaghetti"", ""shrimp"", ""butter"", ""garlic"", ""white wine"", ""chicken broth"", ""lemon"", ""parsley""]"
10,"Classic Beef Chili","[""1 lb. ground beef"", ""1 onion, chopped"", ""1 (15 oz.) can kidney beans, rinsed"", ""1 (15 oz.) can diced tomatoes"", ""1 (8 oz.) can tomato sauce"", ""2 Tbsp. chili powder"", ""1 tsp. cumin""]","[""In a large pot, brown the ground beef and onion. Drain the fat."", ""Stir in the kidney beans, diced tomatoes, tomato sauce, chili powder, and cumin."", ""Bring to a boil, then reduce heat and simmer for at least 1 hour, stirring occasionally.""]","www.example-dinner.com/recipe/10","Generated","[""ground beef"", ""onion"", ""kidney beans"", ""diced tomatoes"", ""tomato sauce"", ""chili powder"", ""cumin""]"
11,"Pot Roast","[""1 (3 lb.) beef chuck roast"", ""1 lb. baby carrots"", ""1 1/2 lbs. small potatoes, halved"", ""1 onion, sliced"", ""1 packet onion soup mix"", ""2 c. beef broth""]","[""Place carrots, potatoes, and onion in the bottom of a slow cooker."", ""Place the chuck roast on top of the vegetables."", ""In a bowl, mix the onion soup mix with the beef broth and pour over the roast."", ""Cover and cook on low for 8-10 hours, or until the roast is tender.""]","www.example-dinner.com/recipe/11","Generated","[""beef chuck roast"", ""carrots"", ""potatoes"", ""onion"", ""onion soup mix"", ""beef broth""]"
12,"Turkey Meatloaf","[""1 1/2 lbs. ground turkey"", ""1 egg"", ""1/2 c. breadcrumbs"", ""1/4 c. ketchup"", ""1 Tbsp. Worcestershire sauce"", ""1 onion, finely chopped""]","[""Preheat oven to 350°F (175°C)."", ""In a large bowl, combine ground turkey, egg, breadcrumbs, 2 Tbsp. ketchup, Worcestershire sauce, and onion. Mix until just combined."", ""Shape the mixture into a loaf and place in a baking dish."", ""Spread the remaining 2 Tbsp. of ketchup over the top of the loaf."", ""Bake for 1 hour, or until cooked through.""]","www.example-dinner.com/recipe/12","Generated","[""ground turkey"", ""egg"", ""breadcrumbs"", ""ketchup"", ""Worcestershire sauce"", ""onion""]"
13,"Pork Chops with Apples","[""4 boneless pork chops"", ""2 apples, cored and sliced"", ""1 onion, sliced"", ""1/2 c. apple cider"", ""1 Tbsp. olive oil"", ""salt and pepper""]","[""Season pork chops with salt and pepper."", ""Heat oil in a large skillet over medium-high heat. Brown the pork chops on both sides and remove from skillet."", ""Add the sliced apples and onion to the skillet. Cook for 5 minutes until softened."", ""Pour in the apple cider, scraping up any browned bits from the bottom of the pan."", ""Return the pork chops to the skillet. Cover, reduce heat, and simmer for 10-15 minutes until pork is cooked through.""]","www.example-dinner.com/recipe/13","Generated","[""pork chops"", ""apples"", ""onion"", ""apple cider"", ""olive oil"", ""salt"", ""pepper""]"
14,"Black Bean Burgers","[""1 (15 oz.) can black beans, rinsed and mashed"", ""1/2 c. breadcrumbs"", ""1 egg"", ""1/2 tsp. cumin"", ""1/2 tsp. garlic powder"", ""4 hamburger buns""]","[""In a bowl, combine the mashed black beans, breadcrumbs, egg, cumin, and garlic powder. Form into 4 patties."", ""Pan-fry the patties in a lightly oiled skillet for 4-5 minutes per side, until heated through and lightly browned."", ""Serve on hamburger buns with your favorite toppings.""]","www.example-dinner.com/recipe/14","Generated","[""black beans"", ""breadcrumbs"", ""egg"", ""cumin"", ""garlic powder"", ""hamburger buns""]"
15,"Chickpea Curry","[""1 Tbsp. coconut oil"", ""1 onion, chopped"", ""2 cloves garlic, minced"", ""1 Tbsp. curry powder"", ""1 (15 oz.) can chickpeas, rinsed"", ""1 (14 oz.) can coconut milk"", ""1 (14 oz.) can diced tomatoes""]","[""Heat coconut oil in a pot over medium heat. Add onion and cook until soft."", ""Stir in garlic and curry powder and cook for 1 minute more."", ""Add the chickpeas, coconut milk, and diced tomatoes. Bring to a simmer."", ""Cook for 15-20 minutes, until the curry has thickened slightly. Serve over rice.""]","www.example-dinner.com/recipe/15","Generated","[""coconut oil"", ""onion"", ""garlic"", ""curry powder"", ""chickpeas"", ""coconut milk"", ""diced tomatoes""]"
16,"Fish Tacos","[""1 lb. white fish fillets (like tilapia or cod), cut into chunks"", ""1 Tbsp. chili powder"", ""8 small corn tortillas"", ""Toppings: shredded cabbage, lime wedges, cilantro, chipotle mayo""]","[""Toss the fish chunks with chili powder, salt, and pepper."", ""Cook the fish in a lightly oiled skillet over medium-high heat for 5-7 minutes, until cooked through and flaky."", ""Warm the corn tortillas."", ""Assemble tacos by filling each tortilla with fish and your desired toppings.""]","www.example-dinner.com/recipe/16","Generated","[""white fish"", ""chili powder"", ""corn tortillas"", ""cabbage"", ""lime"", ""cilantro"", ""chipotle mayo""]"
17,"Classic Lasagna","[""1 lb. ground beef"", ""1 (24 oz.) jar marinara sauce"", ""1 (15 oz.) container ricotta cheese"", ""1 egg"", ""1/2 c. grated Parmesan cheese"", ""9 cooked lasagna noodles"", ""2 c. shredded mozzarella cheese""]","[""Preheat oven to 375°F (190°C)."", ""In a skillet, brown the ground beef. Drain fat and stir in marinara sauce."", ""In a bowl, mix ricotta, egg, and Parmesan cheese."", ""Spread a layer of meat sauce in a 9x13 inch dish. Layer with 3 noodles, then half the ricotta mixture, then a layer of meat sauce."", ""Repeat layers. Top with the final 3 noodles, remaining meat sauce, and sprinkle mozzarella on top."", ""Bake for 30 minutes, then let stand for 10 minutes before serving.""]","www.example-dinner.com/recipe/17","Generated","[""ground beef"", ""marinara sauce"", ""ricotta cheese"", ""egg"", ""Parmesan cheese"", ""lasagna noodles"", ""mozzarella cheese""]"
18,"Stuffed Bell Peppers","[""4 bell peppers, tops cut off and seeds removed"", ""1 lb. ground beef"", ""1/2 c. cooked rice"", ""1/2 onion, chopped"", ""1 (15 oz.) can tomato sauce"", ""1 c. shredded cheddar cheese""]","[""Preheat oven to 350°F (175°C)."", ""In a skillet, brown the ground beef and onion. Drain fat."", ""Stir in the cooked rice and half of the tomato sauce."", ""Stand the bell peppers in a baking dish. Fill each pepper with the beef mixture."", ""Pour the remaining tomato sauce over the filled peppers."", ""Bake for 45 minutes. Top with cheese and bake for another 10 minutes until cheese is melted.""]","www.example-dinner.com/recipe/18","Generated","[""bell peppers"", ""ground beef"", ""rice"", ""onion"", ""tomato sauce"", ""cheddar cheese""]"
19,"Pulled Pork Sandwiches","[""1 (4 lb.) pork shoulder"", ""1 bottle (18 oz.) BBQ sauce"", ""1/2 c. apple cider vinegar"", ""8 hamburger buns""]","[""Place the pork shoulder in a slow cooker."", ""In a bowl, whisk together the BBQ sauce and apple cider vinegar. Pour over the pork."", ""Cover and cook on low for 8-10 hours, until the pork is very tender."", ""Shred the pork with two forks, mixing it with the sauce in the slow cooker."", ""Serve the pulled pork on hamburger buns.""]","www.example-dinner.com/recipe/19","Generated","[""pork shoulder"", ""BBQ sauce"", ""apple cider vinegar"", ""hamburger buns""]"
20,"Beef Stew","[""2 lbs. beef stew meat, cut into 1-inch cubes"", ""1/4 c. flour"", ""2 Tbsp. olive oil"", ""4 c. beef broth"", ""1 lb. small potatoes, quartered"", ""1 lb. carrots, sliced"", ""1 onion, chopped""]","[""Toss the beef cubes with flour, salt, and pepper."", ""Heat oil in a large pot or Dutch oven. Brown the beef in batches and set aside."", ""Add the beef broth to the pot, scraping up any browned bits."", ""Return the beef to the pot. Add potatoes, carrots, and onion."", ""Bring to a boil, then reduce heat, cover, and simmer for 2-3 hours, or until the beef is very tender.""]","www.example-dinner.com/recipe/20","Generated","[""beef stew meat"", ""flour"", ""olive oil"", ""beef broth"", ""potatoes"", ""carrots"", ""onion""]"
21,"Pasta Carbonara","[""1 lb. spaghetti"", ""4 large egg yolks"", ""1 c. grated Pecorino Romano cheese"", ""1/2 lb. pancetta or bacon, diced"", ""2 cloves garlic, minced"", ""black pepper""]","[""Cook spaghetti according to package directions. Reserve 1 cup of pasta water."", ""While pasta cooks, fry the pancetta in a large skillet until crisp. Add garlic and cook for 1 minute. Remove from heat."", ""In a bowl, whisk together the egg yolks and Pecorino cheese."", ""Drain the hot pasta and immediately add it to the skillet with the pancetta. Toss to combine."", ""Slowly pour in the egg and cheese mixture, stirring constantly to create a creamy sauce. Add a splash of reserved pasta water if needed to loosen."", ""Season generously with black pepper and serve immediately.""]","www.example-dinner.com/recipe/21","Generated","[""spaghetti"", ""egg yolks"", ""Pecorino Romano cheese"", ""pancetta"", ""bacon"", ""garlic"", ""pepper""]"
22,"Homemade Pizza","[""1 pre-made pizza crust"", ""1/2 c. pizza sauce"", ""2 c. shredded mozzarella cheese"", ""Your favorite toppings (pepperoni, mushrooms, onions)""]","[""Preheat oven to 425°F (220°C)."", ""Place the pizza crust on a baking sheet."", ""Spread the pizza sauce evenly over the crust, leaving a small border."", ""Sprinkle the mozzarella cheese over the sauce."", ""Add your desired toppings."", ""Bake for 10-15 minutes, or until the crust is golden and the cheese is melted and bubbly.""]","www.example-dinner.com/recipe/22","Generated","[""pizza crust"", ""pizza sauce"", ""mozzarella cheese"", ""pepperoni"", ""mushrooms"", ""onions""]"
23,"Goulash","[""1 lb. ground beef"", ""1 onion, chopped"", ""2 c. elbow macaroni, uncooked"", ""1 (15 oz.) can tomato sauce"", ""1 (15 oz.) can diced tomatoes"", ""2 c. beef broth""]","[""In a large pot, brown the ground beef and onion. Drain fat."", ""Stir in the uncooked macaroni, tomato sauce, diced tomatoes, and beef broth."", ""Bring to a boil, then reduce heat, cover, and simmer for 15-20 minutes, stirring occasionally, until the macaroni is tender.""]","www.example-dinner.com/recipe/23","Generated","[""ground beef"", ""onion"", ""elbow macaroni"", ""tomato sauce"", ""diced tomatoes"", ""beef broth""]"
24,"Chicken Pot Pie","[""1 c. cooked, diced chicken"", ""1 (10 oz.) bag frozen mixed vegetables, thawed"", ""1 (10.5 oz.) can cream of chicken soup"", ""1 refrigerated pie crust""]","[""Preheat oven to 400°F (200°C)."", ""In a bowl, mix together the chicken, mixed vegetables, and cream of chicken soup."", ""Pour the mixture into a 9-inch pie plate."", ""Top with the pie crust, crimping the edges to seal."", ""Cut a few slits in the top of the crust to allow steam to escape."", ""Bake for 30-35 minutes, or until the crust is golden brown and the filling is bubbly.""]","www.example-dinner.com/recipe/24","Generated","[""chicken"", ""mixed vegetables"", ""cream of chicken soup"", ""pie crust""]"
25,"Tuna Noodle Casserole","[""12 oz. egg noodles, cooked"", ""2 cans (5 oz.) tuna, drained"", ""1 (10.5 oz.) can cream of mushroom soup"", ""1 c. frozen peas"", ""1 c. shredded cheddar cheese"", ""1/2 c. breadcrumbs""]","[""Preheat oven to 375°F (190°C)."", ""In a large bowl, combine the cooked noodles, tuna, cream of mushroom soup, peas, and 1/2 cup of the cheese."", ""Pour the mixture into a greased casserole dish."", ""Top with the remaining cheese and the breadcrumbs."", ""Bake for 20-25 minutes, until hot and bubbly.""]","www.example-dinner.com/recipe/25","Generated","[""egg noodles"", ""tuna"", ""cream of mushroom soup"", ""peas"", ""cheddar cheese"", ""breadcrumbs""]"
26,"Sausage and Peppers","[""1 lb. Italian sausage"", ""2 bell peppers, sliced"", ""1 large onion, sliced"", ""1 (15 oz.) can diced tomatoes"", ""6 hoagie rolls""]","[""Cook the Italian sausage in a large skillet until browned. Remove sausage and slice it."", ""In the same skillet, cook the bell peppers and onion until tender."", ""Return the sausage to the skillet. Add the diced tomatoes."", ""Simmer for 10 minutes."", ""Serve the sausage and peppers mixture on hoagie rolls.""]","www.example-dinner.com/recipe/26","Generated","[""Italian sausage"", ""bell peppers"", ""onion"", ""diced tomatoes"", ""hoagie rolls""]"
27,"Chicken Fajitas","[""1 lb. boneless, skinless chicken breast, sliced"", ""2 bell peppers, sliced"", ""1 onion, sliced"", ""1 packet fajita seasoning"", ""8 flour tortillas""]","[""In a large skillet, cook the chicken over medium-high heat until no longer pink."", ""Add the bell peppers and onion to the skillet. Cook for 5-7 minutes until tender-crisp."", ""Stir in the fajita seasoning and a little water according to packet directions."", ""Serve the chicken and vegetable mixture in warm tortillas.""]","www.example-dinner.com/recipe/27","Generated","[""chicken breast"", ""bell peppers"", ""onion"", ""fajita seasoning"", ""flour tortillas""]"
28,"Beef Stroganoff","[""1 lb. beef sirloin, thinly sliced"", ""8 oz. sliced mushrooms"", ""1 onion, chopped"", ""2 Tbsp. butter"", ""1 (10.5 oz.) can cream of mushroom soup"", ""1/2 c. sour cream"", ""cooked egg noodles for serving""]","[""In a large skillet, melt butter and brown the beef. Remove beef from skillet."", ""Add mushrooms and onion to the skillet and cook until tender."", ""Stir in the cream of mushroom soup and bring to a simmer."", ""Reduce heat to low and stir in the sour cream and cooked beef. Heat through but do not boil."", ""Serve over hot egg noodles.""]","www.example-dinner.com/recipe/28","Generated","[""beef sirloin"", ""mushrooms"", ""onion"", ""butter"", ""cream of mushroom soup"", ""sour cream"", ""egg noodles""]"
29,"Lemon Herb Roasted Chicken","[""1 whole chicken (3-4 lbs)"", ""1 lemon, halved"", ""4 sprigs of fresh rosemary"", ""4 cloves garlic, smashed"", ""2 Tbsp. olive oil"", ""salt and pepper""]","[""Preheat oven to 425°F (220°C)."", ""Pat the chicken dry with paper towels. Rub the outside with olive oil and season generously with salt and pepper."", ""Place the lemon halves, rosemary sprigs, and smashed garlic inside the chicken cavity."", ""Roast for 1 hour and 15-30 minutes, or until the juices run clear when a thigh is pierced."", ""Let the chicken rest for 10 minutes before carving.""]","www.example-dinner.com/recipe/29","Generated","[""whole chicken"", ""lemon"", ""rosemary"", ""garlic"", ""olive oil"", ""salt"", ""pepper""]"
30,"Shrimp and Grits","[""1 c. quick-cooking grits"", ""4 c. water"", ""1 lb. shrimp, peeled and deveined"", ""4 slices bacon, chopped"", ""1/2 c. shredded cheddar cheese"", ""2 green onions, sliced""]","[""Cook grits according to package directions. Once cooked, stir in the cheddar cheese."", ""While grits cook, fry the chopped bacon in a skillet until crisp. Remove bacon, leaving the drippings."", ""In the same skillet, cook the shrimp in the bacon drippings for 2-3 minutes until pink."", ""Serve the shrimp over the cheesy grits. Top with the crumbled bacon and sliced green onions.""]","www.example-dinner.com/recipe/30","Generated","[""grits"", ""water"", ""shrimp"", ""bacon"", ""cheddar cheese"", ""green onions""]"
31,"Stuffed Shells","[""1 box (12 oz.) jumbo pasta shells"", ""1 (15 oz.) container ricotta cheese"", ""1 egg"", ""1 c. shredded mozzarella cheese"", ""1/2 c. Parmesan cheese"", ""1 (24 oz.) jar marinara sauce""]","[""Preheat oven to 375°F (190°C). Cook shells according to package directions."", ""In a bowl, mix ricotta, egg, 1/2 cup of mozzarella, and Parmesan cheese."", ""Spread a layer of marinara sauce in a 9x13 inch baking dish."", ""Fill each cooked shell with the cheese mixture and arrange them in the dish."", ""Top with the remaining marinara sauce and mozzarella cheese."", ""Bake for 20-25 minutes until bubbly.""]","www.example-dinner.com/recipe/31","Generated","[""jumbo pasta shells"", ""ricotta cheese"", ""egg"", ""mozzarella cheese"", ""Parmesan cheese"", ""marinara sauce""]"
32,"Chicken and Dumplings","[""1 lb. boneless, skinless chicken breast, cut into chunks"", ""4 c. chicken broth"", ""1 (10.5 oz.) can cream of chicken soup"", ""1 c. frozen peas and carrots"", ""1 can (10 oz.) refrigerated biscuits""]","[""In a large pot, combine chicken broth, cream of chicken soup, and chicken chunks. Bring to a boil."", ""Reduce heat and simmer for 15 minutes."", ""Stir in the frozen peas and carrots."", ""Cut each biscuit into quarters and drop them into the simmering soup."", ""Cover the pot and cook for 10-15 minutes, until the dumplings are cooked through.""]","www.example-dinner.com/recipe/32","Generated","[""chicken breast"", ""chicken broth"", ""cream of chicken soup"", ""peas"", ""carrots"", ""biscuits""]"
33,"Fried Rice","[""3 c. cooked and chilled rice"", ""2 Tbsp. vegetable oil"", ""2 large eggs, whisked"", ""1 c. frozen peas and carrots"", ""1/2 onion, chopped"", ""3 Tbsp. soy sauce""]","[""Heat 1 Tbsp. of oil in a large skillet or wok. Add the whisked eggs and scramble, then remove from the skillet."", ""Add the remaining 1 Tbsp. of oil to the skillet. Add the onion and cook until soft."", ""Stir in the frozen peas and carrots and cook for 2 minutes."", ""Add the chilled rice to the skillet, breaking it up. Stir-fry for 3-5 minutes."", ""Stir in the soy sauce and the scrambled eggs. Mix to combine and serve hot.""]","www.example-dinner.com/recipe/33","Generated","[""rice"", ""vegetable oil"", ""eggs"", ""peas"", ""carrots"", ""onion"", ""soy sauce""]"
"""
PASTA_SHAPES, PASTA_PROTEINS, PASTA_SAUCES = ["Spaghetti", "Penne", "Fettuccine"], [
    "Grilled Chicken", "Italian Sausage", "Meatballs"], ["Marinara", "Alfredo", "Pesto", "Garlic and Oil sauce"]
STIR_FRY_PROTEINS, STIR_FRY_VEGGIES = ["Chicken", "Beef", "Shrimp", "Tofu"], [
    "Broccoli", "Bell Peppers", "Snap Peas", "Mushrooms"]
ROAST_BAKE_PROTEINS, ROAST_BAKE_HERBS = [
    "Chicken Breast", "Salmon Fillet", "Pork Chop"], ["Rosemary", "Dill", "Lemon Pepper"]
TACO_PROTEINS, TACO_TOPPINGS = ["Ground Beef", "Shredded Chicken", "Black Beans"], [
    "Lettuce", "Tomato", "Shredded Cheese", "Salsa"]


def generate_recipe(recipe_id, existing_titles):
    recipe_type = random.choice(
        ["Pasta Dish", "Stir-Fry", "Roasted Main", "Taco Night"])
    title, ingredients_full, instructions, ingredients_clean = "", [], [], []
    if recipe_type == "Pasta Dish":
        shape, protein, sauce = map(
            random.choice, [PASTA_SHAPES, PASTA_PROTEINS, PASTA_SAUCES])
        title = f"{protein} {shape} with {sauce.split(' ')[0].title()}"
        ingredients_full = [
            f"1 lb. {shape}", f"1 lb. {protein}", f"1 jar {sauce}", "Parmesan"]
        instructions = [f"Cook {shape}.", f"Cook {protein}.",
                        f"Combine pasta, protein, and sauce."]
        ingredients_clean = [shape.lower(), protein.lower().replace(
            ' ', '_'), sauce.lower().replace(' ', '_')]
    elif recipe_type == "Stir-Fry":
        protein, veg = map(
            random.choice, [STIR_FRY_PROTEINS, STIR_FRY_VEGGIES])
        title = f"Quick {protein} and {veg} Stir-Fry"
        ingredients_full = [f"1 lb. {protein}",
                            f"2 c. {veg}", "1/4 c. soy sauce", "rice"]
        instructions = [
            f"Heat oil.", f"Cook {protein}.", f"Add {veg} and stir-fry.", f"Add soy sauce. Serve over rice."]
        ingredients_clean = [protein.lower(), veg.lower(), "soy sauce", "rice"]
    elif recipe_type == "Roasted Main":
        protein, herb = map(
            random.choice, [ROAST_BAKE_PROTEINS, ROAST_BAKE_HERBS])
        title = f"{herb.replace(' ', '-')} Baked {protein}"
        ingredients_full = [
            f"4 {protein}s", "2 Tbsp. olive oil", f"1 Tbsp. {herb}", "salt", "pepper"]
        instructions = ["Preheat oven to 400°F.",
                        f"Toss {protein}s with oil and seasonings.", "Bake until cooked."]
        ingredients_clean = [protein.lower().replace(
            ' ', '_'), "olive oil", herb.lower().replace(' ', '_'), "salt", "pepper"]
    elif recipe_type == "Taco Night":
        protein, topping = map(random.choice, [TACO_PROTEINS, TACO_TOPPINGS])
        title = f"Easy {protein.title()} Tacos"
        ingredients_full = [
            f"1 lb. {protein}", "taco seasoning", "12 taco shells", f"1 c. {topping}"]
        instructions = [f"Cook {protein} with seasoning.",
                        "Warm shells.", f"Assemble tacos with {protein} and {topping}."]
        ingredients_clean = [protein.lower().replace(
            ' ', '_'), "taco seasoning", "taco shells", topping.lower()]
    if title in existing_titles:
        title += f" v{random.randint(1, 9)}"
    return {'id': recipe_id, 'title': title, 'ingredients_full': ingredients_full, 'instructions': instructions, 'url': f"www.example-dinner.com/recipe/{recipe_id}", 'source': 'Generated', 'ingredients_clean': ingredients_clean}


def main_generate_csv(num_total_recipes=500):
    output_filepath = 'dinner_recipes_500.csv'
    from io import StringIO
    f = StringIO(BASE_RECIPES_CSV_CONTENT.strip())
    reader = csv.reader(f)
    base_recipes = [{'id': int(row[0]), 'title': row[1], 'ingredients_full': row[2], 'instructions': row[3],
                     'url': row[4], 'source': row[5], 'ingredients_clean': row[6]} for row in reader if row]
    all_generated_recipes = list(base_recipes)
    existing_titles = {recipe['title'] for recipe in base_recipes}
    current_id = len(base_recipes)
    while len(all_generated_recipes) < num_total_recipes:
        new_recipe = generate_recipe(current_id, existing_titles)
        all_generated_recipes.append(new_recipe)
        existing_titles.add(new_recipe['title'])
        current_id += 1
    with open(output_filepath, 'w', newline='', encoding='utf-8') as csvfile:
        writer = csv.writer(csvfile)
        for recipe in all_generated_recipes:
            writer.writerow([recipe['id'], recipe['title'], json.dumps(recipe['ingredients_full']), json.dumps(
                recipe['instructions']), recipe['url'], recipe['source'], json.dumps(recipe['ingredients_clean'])])
    print(
        f"Successfully generated {len(all_generated_recipes)} dinner recipes to '{output_filepath}'!")


if __name__ == '__main__':
    main_generate_csv(num_total_recipes=500)
